name: duckservability
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      # todo: pin this + align the duckdb python version with the version of duckdb we download
      - run: pip3 install dbt-core dbt-duckdb
      - run: which dbt

      # Install DuckDB
      - run: curl -LO 'https://github.com/duckdb/duckdb/releases/download/v0.7.1/duckdb_cli-linux-amd64.zip'
      - run: unzip duckdb_cli-linux-amd64.zip
      - run: mkdir -p ~/.local/bin/ && mv duckdb ~/.local/bin/ && rm duckdb_cli-linux-amd64.zip
      - run: duckdb --version

      # Build the Schema
      - run: dbt build

        
      - name: Archive the generated duckdb file
        uses: actions/upload-artifact@v3
        with:
          name: duckservability.duckdb
          path: build/duckservability.duckdb
