name: duckservability
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
      - run: curl -LO 'https://github.com/duckdb/duckdb/releases/download/v0.7.1/duckdb_cli-linux-amd64.zip'
      - run: unzip duckdb_cli-linux-amd64.zip
      - run: ./duckdb --version
